- name: Copy {{ component }} service file
  ansible.builtin.template :
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service
    # remote_src: yes

- name: Daemon reloading
  ansible.builtin.systemd_service:
    daemon-reload: yes

- name: start and enable {{ component }} service
  ansible.builtin.service:
    name: "{{ component }}"
    state: started
    enabled: yes